include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'

linter:
  rules:
    avoid_print: false
    void_checks: false