// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'promotional_offer.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$PromotionalOffer {
  /// Identifier agreed upon with the App Store for a discount of your choosing.
  String get identifier;

  /// The identifier of the public/private key pair agreed upon with the
  /// App Store when the keys were generated.
  String get keyIdentifier;

  /// One-time use random entropy-adding value for security.
  String get nonce;

  /// The cryptographic signature generated by your private key.
  String get signature;

  /// Timestamp of when the signature is created.
  int get timestamp;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $PromotionalOfferCopyWith<PromotionalOffer> get copyWith =>
      _$PromotionalOfferCopyWithImpl<PromotionalOffer>(
          this as PromotionalOffer, _$identity);

  /// Serializes this PromotionalOffer to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is PromotionalOffer &&
            (identical(other.identifier, identifier) ||
                other.identifier == identifier) &&
            (identical(other.keyIdentifier, keyIdentifier) ||
                other.keyIdentifier == keyIdentifier) &&
            (identical(other.nonce, nonce) || other.nonce == nonce) &&
            (identical(other.signature, signature) ||
                other.signature == signature) &&
            (identical(other.timestamp, timestamp) ||
                other.timestamp == timestamp));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType, identifier, keyIdentifier, nonce, signature, timestamp);

  @override
  String toString() {
    return 'PromotionalOffer(identifier: $identifier, keyIdentifier: $keyIdentifier, nonce: $nonce, signature: $signature, timestamp: $timestamp)';
  }
}

/// @nodoc
abstract mixin class $PromotionalOfferCopyWith<$Res> {
  factory $PromotionalOfferCopyWith(
          PromotionalOffer value, $Res Function(PromotionalOffer) _then) =
      _$PromotionalOfferCopyWithImpl;
  @useResult
  $Res call(
      {String identifier,
      String keyIdentifier,
      String nonce,
      String signature,
      int timestamp});
}

/// @nodoc
class _$PromotionalOfferCopyWithImpl<$Res>
    implements $PromotionalOfferCopyWith<$Res> {
  _$PromotionalOfferCopyWithImpl(this._self, this._then);

  final PromotionalOffer _self;
  final $Res Function(PromotionalOffer) _then;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? identifier = null,
    Object? keyIdentifier = null,
    Object? nonce = null,
    Object? signature = null,
    Object? timestamp = null,
  }) {
    return _then(_self.copyWith(
      identifier: null == identifier
          ? _self.identifier
          : identifier // ignore: cast_nullable_to_non_nullable
              as String,
      keyIdentifier: null == keyIdentifier
          ? _self.keyIdentifier
          : keyIdentifier // ignore: cast_nullable_to_non_nullable
              as String,
      nonce: null == nonce
          ? _self.nonce
          : nonce // ignore: cast_nullable_to_non_nullable
              as String,
      signature: null == signature
          ? _self.signature
          : signature // ignore: cast_nullable_to_non_nullable
              as String,
      timestamp: null == timestamp
          ? _self.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as int,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _PromotionalOffer implements PromotionalOffer {
  const _PromotionalOffer(this.identifier, this.keyIdentifier, this.nonce,
      this.signature, this.timestamp);
  factory _PromotionalOffer.fromJson(Map<String, dynamic> json) =>
      _$PromotionalOfferFromJson(json);

  /// Identifier agreed upon with the App Store for a discount of your choosing.
  @override
  final String identifier;

  /// The identifier of the public/private key pair agreed upon with the
  /// App Store when the keys were generated.
  @override
  final String keyIdentifier;

  /// One-time use random entropy-adding value for security.
  @override
  final String nonce;

  /// The cryptographic signature generated by your private key.
  @override
  final String signature;

  /// Timestamp of when the signature is created.
  @override
  final int timestamp;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$PromotionalOfferCopyWith<_PromotionalOffer> get copyWith =>
      __$PromotionalOfferCopyWithImpl<_PromotionalOffer>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$PromotionalOfferToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _PromotionalOffer &&
            (identical(other.identifier, identifier) ||
                other.identifier == identifier) &&
            (identical(other.keyIdentifier, keyIdentifier) ||
                other.keyIdentifier == keyIdentifier) &&
            (identical(other.nonce, nonce) || other.nonce == nonce) &&
            (identical(other.signature, signature) ||
                other.signature == signature) &&
            (identical(other.timestamp, timestamp) ||
                other.timestamp == timestamp));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType, identifier, keyIdentifier, nonce, signature, timestamp);

  @override
  String toString() {
    return 'PromotionalOffer(identifier: $identifier, keyIdentifier: $keyIdentifier, nonce: $nonce, signature: $signature, timestamp: $timestamp)';
  }
}

/// @nodoc
abstract mixin class _$PromotionalOfferCopyWith<$Res>
    implements $PromotionalOfferCopyWith<$Res> {
  factory _$PromotionalOfferCopyWith(
          _PromotionalOffer value, $Res Function(_PromotionalOffer) _then) =
      __$PromotionalOfferCopyWithImpl;
  @override
  @useResult
  $Res call(
      {String identifier,
      String keyIdentifier,
      String nonce,
      String signature,
      int timestamp});
}

/// @nodoc
class __$PromotionalOfferCopyWithImpl<$Res>
    implements _$PromotionalOfferCopyWith<$Res> {
  __$PromotionalOfferCopyWithImpl(this._self, this._then);

  final _PromotionalOffer _self;
  final $Res Function(_PromotionalOffer) _then;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? identifier = null,
    Object? keyIdentifier = null,
    Object? nonce = null,
    Object? signature = null,
    Object? timestamp = null,
  }) {
    return _then(_PromotionalOffer(
      null == identifier
          ? _self.identifier
          : identifier // ignore: cast_nullable_to_non_nullable
              as String,
      null == keyIdentifier
          ? _self.keyIdentifier
          : keyIdentifier // ignore: cast_nullable_to_non_nullable
              as String,
      null == nonce
          ? _self.nonce
          : nonce // ignore: cast_nullable_to_non_nullable
              as String,
      null == signature
          ? _self.signature
          : signature // ignore: cast_nullable_to_non_nullable
              as String,
      null == timestamp
          ? _self.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as int,
    ));
  }
}

// dart format on
