import 'package:equatable/equatable.dart';

/// The signed discount applied to a payment
class PromotionalOffer extends Equatable {
  /// Identifier agreed upon with the App Store for a discount of your choosing.
  final String identifier;

  /// The identifier of the public/private key pair agreed upon with the App Store when the keys were generated.
  final String keyIdentifier;

  /// One-time use random entropy-adding value for security.
  final String nonce;

  /// The cryptographic signature generated by your private key.
  final String signature;

  /// Timestamp of when the signature is created.
  final int timestamp;

  const PromotionalOffer(
    this.identifier,
    this.keyIdentifier,
    this.nonce,
    this.signature,
    this.timestamp,
  );

  factory PromotionalOffer.fromJson(Map<String, dynamic> json) =>
      PromotionalOffer(
        json['identifier'] as String,
        json['keyIdentifier'] as String,
        json['nonce'] as String,
        json['signature'] as String,
        json['timestamp'] as int,
      );

  Map<String, dynamic> toJson() => {
        'identifier': identifier,
        'keyIdentifier': keyIdentifier,
        'nonce': nonce,
        'signature': signature,
        'timestamp': timestamp,
      };

  @override
  List<Object?> get props => [
        identifier,
        keyIdentifier,
        nonce,
        signature,
        timestamp,
      ];
}
