// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'promotional_offer.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

PromotionalOffer _$PromotionalOfferFromJson(Map<String, dynamic> json) {
  return _PromotionalOffer.fromJson(json);
}

/// @nodoc
mixin _$PromotionalOffer {
  /// Identifier agreed upon with the App Store for a discount of your choosing.
  String get identifier => throw _privateConstructorUsedError;

  /// The identifier of the public/private key pair agreed upon with the
  /// App Store when the keys were generated.
  String get keyIdentifier => throw _privateConstructorUsedError;

  /// One-time use random entropy-adding value for security.
  String get nonce => throw _privateConstructorUsedError;

  /// The cryptographic signature generated by your private key.
  String get signature => throw _privateConstructorUsedError;

  /// Timestamp of when the signature is created.
  int get timestamp => throw _privateConstructorUsedError;

  /// Serializes this PromotionalOffer to a JSON map.
  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  $PromotionalOfferCopyWith<PromotionalOffer> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $PromotionalOfferCopyWith<$Res> {
  factory $PromotionalOfferCopyWith(
          PromotionalOffer value, $Res Function(PromotionalOffer) then) =
      _$PromotionalOfferCopyWithImpl<$Res, PromotionalOffer>;
  @useResult
  $Res call(
      {String identifier,
      String keyIdentifier,
      String nonce,
      String signature,
      int timestamp});
}

/// @nodoc
class _$PromotionalOfferCopyWithImpl<$Res, $Val extends PromotionalOffer>
    implements $PromotionalOfferCopyWith<$Res> {
  _$PromotionalOfferCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? identifier = null,
    Object? keyIdentifier = null,
    Object? nonce = null,
    Object? signature = null,
    Object? timestamp = null,
  }) {
    return _then(_value.copyWith(
      identifier: null == identifier
          ? _value.identifier
          : identifier // ignore: cast_nullable_to_non_nullable
              as String,
      keyIdentifier: null == keyIdentifier
          ? _value.keyIdentifier
          : keyIdentifier // ignore: cast_nullable_to_non_nullable
              as String,
      nonce: null == nonce
          ? _value.nonce
          : nonce // ignore: cast_nullable_to_non_nullable
              as String,
      signature: null == signature
          ? _value.signature
          : signature // ignore: cast_nullable_to_non_nullable
              as String,
      timestamp: null == timestamp
          ? _value.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as int,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$PromotionalOfferImplCopyWith<$Res>
    implements $PromotionalOfferCopyWith<$Res> {
  factory _$$PromotionalOfferImplCopyWith(_$PromotionalOfferImpl value,
          $Res Function(_$PromotionalOfferImpl) then) =
      __$$PromotionalOfferImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {String identifier,
      String keyIdentifier,
      String nonce,
      String signature,
      int timestamp});
}

/// @nodoc
class __$$PromotionalOfferImplCopyWithImpl<$Res>
    extends _$PromotionalOfferCopyWithImpl<$Res, _$PromotionalOfferImpl>
    implements _$$PromotionalOfferImplCopyWith<$Res> {
  __$$PromotionalOfferImplCopyWithImpl(_$PromotionalOfferImpl _value,
      $Res Function(_$PromotionalOfferImpl) _then)
      : super(_value, _then);

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? identifier = null,
    Object? keyIdentifier = null,
    Object? nonce = null,
    Object? signature = null,
    Object? timestamp = null,
  }) {
    return _then(_$PromotionalOfferImpl(
      null == identifier
          ? _value.identifier
          : identifier // ignore: cast_nullable_to_non_nullable
              as String,
      null == keyIdentifier
          ? _value.keyIdentifier
          : keyIdentifier // ignore: cast_nullable_to_non_nullable
              as String,
      null == nonce
          ? _value.nonce
          : nonce // ignore: cast_nullable_to_non_nullable
              as String,
      null == signature
          ? _value.signature
          : signature // ignore: cast_nullable_to_non_nullable
              as String,
      null == timestamp
          ? _value.timestamp
          : timestamp // ignore: cast_nullable_to_non_nullable
              as int,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$PromotionalOfferImpl implements _PromotionalOffer {
  const _$PromotionalOfferImpl(this.identifier, this.keyIdentifier, this.nonce,
      this.signature, this.timestamp);

  factory _$PromotionalOfferImpl.fromJson(Map<String, dynamic> json) =>
      _$$PromotionalOfferImplFromJson(json);

  /// Identifier agreed upon with the App Store for a discount of your choosing.
  @override
  final String identifier;

  /// The identifier of the public/private key pair agreed upon with the
  /// App Store when the keys were generated.
  @override
  final String keyIdentifier;

  /// One-time use random entropy-adding value for security.
  @override
  final String nonce;

  /// The cryptographic signature generated by your private key.
  @override
  final String signature;

  /// Timestamp of when the signature is created.
  @override
  final int timestamp;

  @override
  String toString() {
    return 'PromotionalOffer(identifier: $identifier, keyIdentifier: $keyIdentifier, nonce: $nonce, signature: $signature, timestamp: $timestamp)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$PromotionalOfferImpl &&
            (identical(other.identifier, identifier) ||
                other.identifier == identifier) &&
            (identical(other.keyIdentifier, keyIdentifier) ||
                other.keyIdentifier == keyIdentifier) &&
            (identical(other.nonce, nonce) || other.nonce == nonce) &&
            (identical(other.signature, signature) ||
                other.signature == signature) &&
            (identical(other.timestamp, timestamp) ||
                other.timestamp == timestamp));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode => Object.hash(
      runtimeType, identifier, keyIdentifier, nonce, signature, timestamp);

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  @pragma('vm:prefer-inline')
  _$$PromotionalOfferImplCopyWith<_$PromotionalOfferImpl> get copyWith =>
      __$$PromotionalOfferImplCopyWithImpl<_$PromotionalOfferImpl>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$PromotionalOfferImplToJson(
      this,
    );
  }
}

abstract class _PromotionalOffer implements PromotionalOffer {
  const factory _PromotionalOffer(
      final String identifier,
      final String keyIdentifier,
      final String nonce,
      final String signature,
      final int timestamp) = _$PromotionalOfferImpl;

  factory _PromotionalOffer.fromJson(Map<String, dynamic> json) =
      _$PromotionalOfferImpl.fromJson;

  /// Identifier agreed upon with the App Store for a discount of your choosing.
  @override
  String get identifier;

  /// The identifier of the public/private key pair agreed upon with the
  /// App Store when the keys were generated.
  @override
  String get keyIdentifier;

  /// One-time use random entropy-adding value for security.
  @override
  String get nonce;

  /// The cryptographic signature generated by your private key.
  @override
  String get signature;

  /// Timestamp of when the signature is created.
  @override
  int get timestamp;

  /// Create a copy of PromotionalOffer
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  _$$PromotionalOfferImplCopyWith<_$PromotionalOfferImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
