allprojects {
    repositories {
        google()
        mavenCentral()
        // TODO: remove before merging, together with the purchases 11.0.0-SNAPSHOT pins.
        maven {
            url 'https://central.sonatype.com/repository/maven-snapshots/'
            content { includeGroup 'com.revenuecat.purchases' }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
